In [48]:
import pandas as pd 
import numpy as np 

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.decomposition import PCA

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_excel("Mi raw data.xlsx")

In [3]:
df.head()

Customer ID       Day            Browser  No. of Clicks  Pages Viewed  \
0            1    Monday             Chrome             13             4   
1            2  Saturday             Chrome             15             5   
2            3    Monday  Internet Explorer             20             6   
3            4    Monday             Chrome             42             6   
4            5  Saturday  Internet Explorer             20             6   

   Time (min)  Amount Spent (Rs.)  Unnamed: 7 Unnamed: 8  
0         8.5              2668.0         NaN        NaN  
1        16.9              3469.0         NaN        NaN  
2         7.3              5215.0         NaN        NaN  
3        30.1             10423.0         NaN        NaN  
4        13.3              5404.0         NaN        NaN

In [5]:
df.drop(["Customer ID","Unnamed: 7","Unnamed: 8"],axis=1,inplace=True)

In [7]:
le = LabelEncoder()
df["Day"] = le.fit_transform(df["Day"])
df["Browser"] = le.fit_transform(df["Browser"])

In [38]:
X = df.drop("Amount Spent (Rs.)",axis=1)
y= df[["Amount Spent (Rs.)"]]

In [12]:
df.columns

Index(['Day', 'Browser', 'No. of Clicks', 'Pages Viewed', 'Time (min)',
       'Amount Spent (Rs.)'],
      dtype='object')

In [20]:
sc =StandardScaler()
sc_fit= sc.fit_transform(X)

In [23]:
sc_fit

array([[-0.75292749, -0.83205029, -1.29905458, -0.4065788 , -0.71804916],
       [-0.2763911 , -0.83205029, -1.05714497,  0.08924901,  0.681397  ],
       [-0.75292749,  1.94145069, -0.45237096,  0.58507681, -0.91797004],
       ...,
       [-1.22946388,  0.5547002 ,  0.63622226,  2.56838805,  3.34700874],
       [-0.75292749,  1.94145069, -0.45237096,  0.58507681, -0.91797004],
       [ 1.62975445, -0.83205029,  0.63622226, -0.4065788 , -0.25156711]])

In [21]:
pca = PCA()
pca_X= pca.fit_transform(sc_fit)

In [22]:
pca_X

array([[-1.23082708,  0.21403565, -1.10028021,  0.89559756,  0.23279418],
       [-0.2742681 , -0.69597293, -0.43052995,  1.25805677, -0.17566533],
       [ 0.28305213,  2.26510403,  0.51785439,  0.34741105,  0.35506559],
       ...,
       [ 3.95730703, -0.70175365,  0.30463554,  1.86696608, -0.54040256],
       [ 0.28305213,  2.26510403,  0.51785439,  0.34741105,  0.35506559],
       [-0.69304949, -1.31688937,  0.59526317, -1.13330997,  0.35851554]])

In [24]:
pca.explained_variance_ratio_

array([0.46153389, 0.21085949, 0.17362483, 0.08927177, 0.06471003])

In [25]:
np.cumsum(pca.explained_variance_ratio_)

array([0.46153389, 0.67239338, 0.84601821, 0.93528997, 1.        ])

In [26]:
pca_df = pd.DataFrame(pca_X, columns=["PC1","PC2","PC3","PC4","PC5"])

In [27]:
pca_df

PC1       PC2       PC3       PC4       PC5
0     -1.230827  0.214036 -1.100280  0.895598  0.232794
1     -0.274268 -0.695973 -0.430530  1.258057 -0.175665
2      0.283052  2.265104  0.517854  0.347411  0.355066
3      2.999354 -1.879474 -0.712616 -0.346029 -1.273154
4      0.628870  1.577554  1.065200  0.593397 -0.168274
...         ...       ...       ...       ...       ...
43195  0.208075 -0.183903 -1.659924 -0.655061 -0.733100
43196 -1.230827  0.214036 -1.100280  0.895598  0.232794
43197  3.957307 -0.701754  0.304636  1.866966 -0.540403
43198  0.283052  2.265104  0.517854  0.347411  0.355066
43199 -0.693049 -1.316889  0.595263 -1.133310  0.358516

[43200 rows x 5 columns]

In [40]:
X_train,X_test,y_train,y_test = train_test_split(pca_df,y, test_size= 0.2, random_state= 5)

In [49]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [50]:
lr_pred = lr.predict(X_test)

In [51]:
accuracy_score(y_test,lr_pred)

ValueError: continuous is not supported